repos:
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        args: ["--rules", "~MD013"]
        files: \.(md|mdown|markdown)$
  - repo: local
    hooks:
      - id: secretlint
        name: Secretlint
        language: docker_image
        entry: secretlint/secretlint:latest secretlint
