# See options at https://github.com/coogie/oscailte
# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://github.com/Pyhive
baseurl: /pyhiveapi.docs
title: Pyhiveapi
subtitle: Hive integration libary
author: Pyhiveapi
simple_search: https://www.google.com/search
description: Python libary to interface with Hive.
theme: jekyll-theme-slate

permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
sass:
  sass_dir: _sass

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

plugins:
  - jekyll-time-to-read
  - jekyll-toc
  - jekyll-redirect-from
  - jekyll-relative-links
