name: Pyhiveapi Docs

on: [push, pull_request]

jobs:
  code-lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@v2
      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  secretlint:
    name: "Secretlint"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npm install
          npm install husky lint-staged
          npm install secretlint @secretlint/secretlint-rule-preset-recommend --save-dev
          npm install @secretlint/secretlint-rule-basicauth  --save-dev
          npm install @secretlint/secretlint-rule-pattern  --save-dev
          npm install @secretlint/secretlint-rule-no-homedir  --save-dev
      - name: Lint with Secretlint
        run: npx secretlint "**/*"
  build:
    name: Jekyll build
    runs-on: ubuntu-latest
    needs: [code-lint]
    steps:
      - name: Check out files from GitHub
        uses: actions/checkout@v2
      - name: Setting up Ruby 2.6
        uses: ruby/setup-ruby@v1.66.0
        with:
          ruby-version: 2.6
      - name: Setup Ruby Gems cache
        uses: actions/cache@v2.1.4
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-
      - name: Installing dependencies
        run: |
          bundle install
      - name: Setting up Jekyll cache
        uses: actions/cache@v2.1.4
        with:
          path: source/.jekyll-cache
          key: jekyll-${{ hashFiles('**/Gemfile.lock') }}-${{
            hashFiles('**/_config.yml') }}
          restore-keys: |
            jekyll-${{ hashFiles('**/Gemfile.lock') }}-
            jekyll-
      - name: Building site
        run: |
          bundle exec jekyll serve
